# name_conversion_dict.py


import sqlalchemy as sal

# CSV name : DB name
col_names_dict = {
    "list_id": "id",
    "location_id": "location_id",
    "status_code": "location_status_id",
    "tree_cover_loss_total_yearly": "tree_cover_loss_total_yearly",
    "tree_cover_loss_primary_forest_yearly": "tree_cover_loss_primary_forest_yearly",
    "tree_cover_loss_peat_yearly": "tree_cover_loss_peat_yearly",
    "tree_cover_loss_intact_forest_yearly": "tree_cover_loss_intact_forest_yearly",
    "tree_cover_loss_protected_areas_yearly": "tree_cover_loss_protected_areas_yearly",
    "tree_cover_loss_sea_landcover_yearly": "tree_cover_loss_sea_landcover_yearly",
    "tree_cover_loss_idn_landcover_yearly": "tree_cover_loss_idn_landcover_yearly",
    "tree_cover_loss_soy_yearly": "tree_cover_loss_soy_yearly",
    "tree_cover_loss_idn_legal_yearly": "tree_cover_loss_idn_legal_yearly",
    "tree_cover_loss_idn_forest_moratorium_yearly": "tree_cover_loss_idn_forest_moratorium_yearly",
    "tree_cover_loss_prodes_yearly": "tree_cover_loss_prodes_yearly",
    "tree_cover_loss_prodes_wdpa_yearly": "tree_cover_loss_prodes_wdpa_yearly",
    "tree_cover_loss_prodes_primary_forest_yearly": "tree_cover_loss_prodes_primary_forest_yearly",
    "tree_cover_loss_brazil_biomes_yearly": "tree_cover_loss_brazil_biomes_yearly",
    "tree_cover_extent_total": "tree_cover_extent_total",
    "tree_cover_extent_protected_areas": "tree_cover_extent_protected_areas",
    "tree_cover_extent_peat": "tree_cover_extent_peat",
    "tree_cover_extent_intact_forest": "tree_cover_extent_intact_forest",
    "natural_habitat_primary": "natural_habitat_primary",
    "natural_habitat_intact_forest": "natural_habitat_intact_forest",
    "total_area": "total_area",
    "protected_areas_area": "protected_areas_area",
    "peat_area": "peat_area",
    "arg_otbn_area": "arg_otbn_area",
    "brazil_biomes": "brazil_biomes",
    "idn_legal_area": "idn_legal_area",
    "sea_landcover_area": "sea_landcover_area",
    "idn_landcover_area": "idn_landcover_area",
    "idn_forest_moratorium_area": "idn_forest_moratorium_area",
    "south_america_presence": "south_america_presence",
    "legal_amazon_presence": "legal_amazon_presence",
    "brazil_biomes_presence": "brazil_biomes_presence",
    "cerrado_biome_presence": "cerrado_biome_presence",
    "southeast_asia_presence": "southeast_asia_presence",
    "indonesia_presence": "indonesia_presence",
    "argentina_presence": "argentina_presence",
    "commodity_value_forest_extent": "commodity_value_forest_extent_level",
    "commodity_value_peat": "commodity_value_peat_level",
    "commodity_value_protected_areas": "commodity_value_protected_areas_level",
    "commodity_threat_deforestation": "commodity_threat_deforestation",
    "commodity_threat_peat": "commodity_threat_peat",
    "commodity_threat_protected_areas": "commodity_threat_protected_areas",
    "commodity_threat_fires": "commodity_threat_fires",
}


# DB column name : Data type
db_schema_dict = {
    "id": sal.INTEGER,
    "location_id": sal.INTEGER,
    "location_status_id": sal.INTEGER,
    "tree_cover_loss_total_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_primary_forest_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_peat_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_intact_forest_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_protected_areas_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_sea_landcover_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_idn_landcover_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_idn_primary_forest_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_soy_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_idn_legal_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_idn_forest_moratorium_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_prodes_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_prodes_wdpa_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_prodes_primary_forest_yearly": sal.NVARCHAR(length=None),
    "tree_cover_loss_brazil_biomes_yearly": sal.NVARCHAR(length=None),
    "tree_cover_extent_total": sal.DECIMAL(18, 6),
    "tree_cover_extent_primary_forest": sal.DECIMAL(18, 6),
    "tree_cover_extent_protected_areas": sal.DECIMAL(18, 6),
    "tree_cover_extent_peat": sal.DECIMAL(18, 6),
    "tree_cover_extent_intact_forest": sal.DECIMAL(18, 6),
    "natural_habitat_primary": sal.DECIMAL(18, 6),
    "natural_habitat_intact_forest": sal.DECIMAL(18, 6),
    "natural_habitat_global_land_cover": sal.NVARCHAR(length=None),
    "total_area": sal.DECIMAL(18, 6),
    "protected_areas_area": sal.DECIMAL(18, 6),
    "critical_habitat_alliance_zero": sal.DECIMAL(18, 6),
    "indigenous_people_land_rights": sal.DECIMAL(18, 6),
    "peat_area": sal.DECIMAL(18, 6),
    "fires_counts_monthly": sal.NVARCHAR(length=None),
    "soy_total_area": sal.NVARCHAR(length=None),
    "soy_pre2001_nonforest_area": sal.DECIMAL(18, 6),
    "brazil_biomes": sal.NVARCHAR(length=None),
    "idn_legal_area": sal.NVARCHAR(length=None),
    "sea_landcover_area": sal.NVARCHAR(length=None),
    "idn_landcover_area": sal.NVARCHAR(length=None),
    "idn_forest_moratorium_area": sal.DECIMAL(18, 6),
    "south_america_presence": sal.NVARCHAR(length=None),
    "legal_amazon_presence": sal.NVARCHAR(length=None),
    "brazil_biomes_presence": sal.NVARCHAR(length=None),
    "cerrado_biome_presence": sal.NVARCHAR(length=None),
    "southeast_asia_presence": sal.NVARCHAR(length=None),
    "indonesia_presence": sal.NVARCHAR(length=None),
    "commodity_threat_deforestation_level": sal.NVARCHAR(length=None),
    "commodity_threat_peat_level": sal.NVARCHAR(length=None),
    "commodity_threat_protected_areas_level": sal.NVARCHAR(length=None),
    "commodity_threat_fires_level": sal.NVARCHAR(length=None),
    "commodity_threat_overall_level": sal.NVARCHAR(length=None),
    "commodity_threat_overall_score": sal.NVARCHAR(length=None),
    "commodity_value_forest_extent_level": sal.NVARCHAR(length=None),
    "commodity_value_peat_level": sal.NVARCHAR(length=None),
    "commodity_value_protected_areas_level": sal.NVARCHAR(length=None),
    "commodity_value_overall_level": sal.NVARCHAR(length=None),
    "commodity_value_overall_score": sal.NVARCHAR(length=None),
    "commodity_value_forest_extent": sal.NVARCHAR(length=None),
    "commodity_value_peat": sal.NVARCHAR(length=None),
    "commodity_value_protected_areas": sal.NVARCHAR(length=None),
    "commodity_mill_priority_level": sal.NVARCHAR(length=None),
    "commodity_mill_priority_score": sal.NVARCHAR(length=None),
    "commodity_threat_deforestation": sal.NVARCHAR(length=None),
    "commodity_threat_peat": sal.NVARCHAR(length=None),
    "commodity_threat_protected_areas": sal.NVARCHAR(length=None),
    "commodity_threat_fires": sal.NVARCHAR(length=None),
    "dissolved_data_location_info": sal.NVARCHAR(length=None),
    "tree_cover_loss_arg_otbn_yearly": sal.NVARCHAR(length=None),
    "arg_otbn_area": sal.NVARCHAR(length=None),
    "argentina_presence": sal.NVARCHAR(length=None),
}
