conn_string = ""

analysis_path = r""
list_number = 3

small_lists_columns = [
        "id",
        "location_id",
        "location_status_id",
        "tree_cover_loss_total_yearly",
        "tree_cover_loss_primary_forest_yearly",
        "tree_cover_loss_peat_yearly",
        "tree_cover_loss_intact_forest_yearly",
        "tree_cover_loss_protected_areas_yearly",
        "tree_cover_loss_sea_landcover_yearly",
        "tree_cover_loss_idn_landcover_yearly",
        #"tree_cover_loss_idn_primary_forest_yearly",
        "tree_cover_loss_soy_yearly",
        #"tree_cover_loss_idn_legal_yearly",
        "tree_cover_loss_idn_forest_moratorium_yearly",
        "tree_cover_loss_prodes_yearly",
        "tree_cover_loss_prodes_wdpa_yearly",
        "tree_cover_loss_prodes_primary_forest_yearly",
        "tree_cover_loss_brazil_biomes_yearly",
        "tree_cover_extent_total",
        "tree_cover_extent_primary_forest",
        "tree_cover_extent_protected_areas",
        "tree_cover_extent_peat",
        "tree_cover_extent_intact_forest",
        "natural_habitat_primary",
        "natural_habitat_intact_forest",
        #"natural_habitat_global_land_cover",
        "total_area",
        "protected_areas_area",
        #"critical_habitat_alliance_zero",
        #"indigenous_people_land_rights",
        "peat_area",
        #"fires_counts_monthly",
        #"soy_total_area",
        #"soy_pre2001_nonforest_area",
        "brazil_biomes",
        "idn_legal_area",
        "sea_landcover_area",
        "idn_landcover_area",
        "idn_forest_moratorium_area",
        "south_america_presence",
        "legal_amazon_presence",
        "brazil_biomes_presence",
        "cerrado_biome_presence",
        "southeast_asia_presence",
        "indonesia_presence"
        ]

# specify column in database table (list_id must be last!!!!)
small_lists_list_level_columns = [
        'status_id',
        'tree_cover_loss_total_yearly',
        'tree_cover_loss_primary_forest_yearly',
        'tree_cover_loss_peat_yearly',
        'tree_cover_loss_intact_forest_yearly',
        'tree_cover_loss_protected_areas_yearly',
        'tree_cover_loss_sea_landcover_yearly',
        'tree_cover_loss_idn_landcover_yearly',
        'tree_cover_loss_soy_yearly',
        'tree_cover_loss_idn_legal_yearly',
        'tree_cover_loss_idn_forest_moratorium_yearly',
        'tree_cover_loss_prodes_yearly',
        'tree_cover_loss_prodes_wdpa_yearly',
        'tree_cover_loss_prodes_primary_forest_yearly',
        'tree_cover_loss_brazil_biomes_yearly',
        'tree_cover_extent_total',
        'tree_cover_extent_primary_forest',
        'tree_cover_extent_protected_areas',
        'tree_cover_extent_peat',
        'tree_cover_extent_intact_forest',
        'natural_habitat_primary',
        'natural_habitat_intact_forest',
        'total_area',
        'protected_areas_area',
        'peat_area',
        'brazil_biomes',
        'idn_legal_area',
        'sea_landcover_area',
        'idn_landcover_area',
        'idn_forest_moratorium_area',
        'south_america_presence',
        'legal_amazon_presence',
        'brazil_biomes_presence',
        'cerrado_biome_presence',
        'southeast_asia_presence',
        'indonesia_presence',
        'commodity_threat_deforestation',
        'list_id'
        ]